[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=7.1"]
build-backend = "setuptools.build_meta"

[project]
name = "flask-journal"
authors = [
  { name="Jason Ross", email="github@csfreak.com" },
]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Framework :: Flask",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
]
dynamic = ["version", "dependencies"]

[project.optional-dependencies]
deploy = ['gunicorn>=20.0.0']

[project.urls]
"Homepage" = "https://github.com/csfreak/flask-journal"
"Bug Tracker" = "https://github.com/csfreak/flask-journal"

[tool.setuptools.packages.find]
where = ['src']
include = ["flask_journal*"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools_scm]
version_scheme = "python-simplified-semver"
local_scheme = "no-local-version"

[tool.flake8]
max-line-length = 80
max-complexity = 10
exclude = [
    '.git',       # No need to traverse our git directory
    '.venv',      # No need to scan imported code
    '.vscode',    # This is autogenerated and managed by vscode
    'migrations', # This is autogenerated
]
extend-ignore = ['E501', 'E203']
extend-select = ['B950']

[tool.black]
max_line_length = 80
extend-exclude = 'migrations'  # This is autogenerated

[tool.isort]
profile = "black"
extend_skip = ["migrations"]

[tool.pytest.ini_options]
testpaths = "test"
python_files = "test_*.py"
log_level = 'DEBUG'
addopts = "--capture=sys --cov=flask_journal --junitxml=.pytest.xml -n auto"
filterwarnings = [
    "ignore:'get_token_status' is deprecated - use check_and_get_token_status instead:DeprecationWarning:flask_security",
    "ignore: 'flask.Markup' is deprecated and will be removed in Flask 2.4. Import 'markupsafe.Markup' instead.:DeprecationWarning:flask_security",
    "ignore: 'flask.Markup' is deprecated and will be removed in Flask 2.4. Import 'markupsafe.Markup' instead.:DeprecationWarning:flask_wtf",
    "ignore: 'crypt' is deprecated and slated for removal in Python 3.13:DeprecationWarning:passlib",
    "ignore: pkg_resources is deprecated as an API:DeprecationWarning"
]
markers = []

[tool.coverage.run]
branch = true
source_pkgs = ["flask_journal"]
omit = [ 
    "**/flask_journal/logging.py",
]
[tool.coverage.paths]
src = [
    "src/flask_journal/",
    "flask_journal/"
    ]

[tool.coverage.report]
show_missing = true
skip_empty = true
fail_under = 95
exclude_also = [
    "pass",
    "def __str__",
    "def __repr__",
    "debug",
    "logger.debug"
]

[tool.coverage.lcov]
output = 'coverage.lcov'

[tool.coverage.xml]
output = 'coverage.xml'

