"""Add Support for Shared Entry
Revision ID: c2433ae45adf
Revises: 6d1ce7616b63
Create Date: 2023-12-07 20:02:41.844904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c2433ae45adf"
down_revision = "1594ebf10015"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(255)))
        batch_op.create_unique_constraint("uq_user_name", ["name"])

    op.create_table(
        "shared_entry",
        sa.Column("entry_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["entry.id"], name=op.f("fk_shared_entry_entry_id_entry")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_shared_entry_user_id_user")
        ),
        sa.UniqueConstraint(
            "entry_id", "user_id", name=op.f("uq_shared_entry_entry_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shared_entry")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("name")
        batch_op.drop_constraint("uq_user_name")
    # ### end Alembic commands ###
