"""Add Support For Entry Sharing

Revision ID: 1fbdb95e0d10
Revises: 877a40556834
Create Date: 2023-10-06 14:06:20.250732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1fbdb95e0d10"
down_revision = "d0551f9f68ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(batch_op.f("uq_user_name"), ["name"])

    with op.batch_alter_table("entry", schema=None) as batch_op:
        batch_op.add_column(sa.Column("public", sa.Boolean(), nullable=False))

    op.create_table(
        "shared_entries",
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["entry.id"], name=op.f("fk_shared_entries_entry_id_entry")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_shared_entries_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shared_entries")),
        sa.UniqueConstraint(
            "entry_id", "user_id", name=op.f("uq_shared_entries_entry_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_user_name"), type_="unique")
        batch_op.drop_column("name")
    with op.batch_alter_table("entry", schema=None) as batch_op:
        batch_op.drop_column("public")
    op.drop_table("shared_entries")
    # ### end Alembic commands ###
