"""empty message

Revision ID: d0551f9f68ce
Revises: 40e364e4a0df
Create Date: 2023-08-20 17:58:12.461031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d0551f9f68ce"
down_revision = "40e364e4a0df"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("home_tags", sa.Boolean(), nullable=False, default=True)
        )
        batch_op.add_column(
            sa.Column("home_preview", sa.Boolean(), nullable=False, default=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.drop_column("home_preview")
        batch_op.drop_column("home_tags")

    # ### end Alembic commands ###
