"""empty message

Revision ID: 40e364e4a0df
Revises: 12aa0adaa78d
Create Date: 2023-07-17 16:02:28.228342

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "40e364e4a0df"
down_revision = "12aa0adaa78d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "theme",
                sa.Enum(
                    "default",
                    "cerulean",
                    "cosmo",
                    "cyborg",
                    "darkly",
                    "flatly",
                    "journal",
                    "litera",
                    "lumen",
                    "lux",
                    "materia",
                    "minty",
                    "morph",
                    "pulse",
                    "quartz",
                    "sandstone",
                    "simplex",
                    "sketchy",
                    "slate",
                    "solar",
                    "spacelab",
                    "superhero",
                    "united",
                    "vapor",
                    "yeti",
                    "zephyr",
                    name="theme",
                ),
                nullable=False,
            )
        )
        batch_op.drop_column("encrypt_entries")
        batch_op.drop_column("encryption_key")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("encryption_key", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("encrypt_entries", sa.BOOLEAN(), nullable=False))
        batch_op.drop_column("theme")

    # ### end Alembic commands ###
