name: Dev Build
on:
  push:
    branches:
      - dev
    paths:
      - "flask_journal"
      - "migrations"
      - "scripts"
      - "Dockerfile"
      - "LICENSE"
      - "requirements.txt"
      - "pyproject.toml"

permissions:
  checks: read
  contents: read
  packages: write
env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            test/requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Python Build
        id: build
        run: |
          python -m build
          VERSION=$(ls dist/flask-journal-*.tar.gz | sed 's/dist\/flask-journal-\(.*\).tar.gz/\1/')
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: flask_journal
          tags: >
            ${{ github.sha }}
            v${{ steps.build.outputs.version }}-${{ github.sha }}
          containerfiles: |
            ./Dockerfile
          oci: true
      # Push the image to GHCR (Image Registry)
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
