name: Python Checks

on:
  pull_request:
    branches:
      - "main"
      - "dev"
    paths:
      - "**.py"
      - "**requirements.txt"

permissions:
  checks: write
  contents: read

jobs:
  flake8:
    runs-on: ubuntu-latest
    name: Run flake8
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            test/requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test/requirements.txt
      - uses: psf/black@stable
        with:
          options: --check --verbose --color
          src: "./src"
      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 ./src --count --show-source --statistics
      - name: Check imports with isort
        run: |
          isort -c --diff ./src
  test:
    runs-on: ubuntu-latest
    name: Run pytest and report test coverage
    needs: flake8
    permissions:
      checks: write
      contents: read
      issues: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            test/requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r test/requirements.txt
      - name: Tests
        run: |
          py.test --cov-report=xml

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: coverage.xml
          junitxml-path: ./.pytest.xml
  build:
    runs-on: ubuntu-latest
    name: Run Buildah
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            test/requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Python Build
        id: build
        run: |
          python -m build
          echo "version=$(ls dist/flask-journal-*.tar.gz | sed 's/dist\/flask-journal-\(.*\).tar.gz/\1/')" >> "$GITHUB_OUTPUT"
      - name: Buildah
        uses: redhat-actions/buildah-build@v2
        with:
          image: flask_journal
          tags: ${{ github.sha }}
          containerfiles: |
            ./Dockerfile
          oci: true
      - uses: actions/upload-artifact@v3
        with:
          name: build ${{steps.build.outputs.version}}
          path: dist/
