name: Build and Release
on:
  push:
    branches:
      - main
    paths:
      - "flask_journal"
      - "migrations"
      - "scripts"
      - "Dockerfile"
      - "LICENSE"
      - "requirements.txt"
      - "pyproject.toml"

permissions:
  checks: write
  contents: read
  packages: write
env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Semantic Release
        id: release_version
        uses: go-semantic-release/action@v1.21.0
        with:
          github-token: ${{ github.token }}
          allow-initial-development-versions: true
          force-bump-patch-version: true
      - name: SetVersion
        id: version
        run: |
          version=${{ steps.release_version.outputs.version }}
          echo $version > VERSION
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: flask_journal
          tags: >
            ${{ github.sha }}
            v${{ steps.release_version.outputs.version }}
            v${{ steps.release_version.outputs.version_major }}
            v${{ steps.release_version.outputs.version_major }}.${{ steps.release_version.outputs.version_minor }}
          containerfiles: |
            ./Dockerfile
          build-args: |
            APP_VERSION=${{ needs.release.outputs.version }}
          oci: true
      # Push the image to GHCR (Image Registry)
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
